### ISSUE TITLE
'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by frakman1** [Wingman4l7/relisterine#3]
I kept running into this issue when running it after installing selenium for the first time on my Mac (High Sierra)

```python
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

I had to change this line : 

```python
chromedriver = webdriver.Chrome('/Python27/selenium/webdriver/chromedriver', chrome_options=opts)
```

to include the path to where I installed my `chromedriver` which I installed using: `brew cask install chromedriver`)

```python
chromedriver = webdriver.Chrome(executable_path='/usr/local/bin/chromedriver', chrome_options=opts)
```

**Comment by Wingman4l7** [comment]
Thanks for the reminder on this, it's probably the most common error people will face who haven't used chromedriver for.  I'll add a note in the README and modify the code to include the name of the argument (`executable_path=`).
