### ISSUE TITLE
Message: unknown error: call function result missing 'value'

### ISSUE THREAD

**Issue by frakman1** [Wingman4l7/relisterine#4]
I ran into this error when trying this on my Ubuntu 18.04 linux box.

```
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=77.0.3865.120)
  (Driver info: chromedriver=2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3),platform=Linux 5.0.0-29-generic x86_64)
```
The trick as to find the right combination of chromedriver + chrome that work together correctly.
For me, it was [chromedriver version 2.46](https://chromedriver.storage.googleapis.com/index.html?path=2.46/) and [chrome version 75.0.3770.142](https://confuzer.cloud/mirror/dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_75.0.3770.142-1_amd64.deb)

Be sure to uninstall your existing chrome first (mine was version 77.x) using:
```bash
    sudo apt-get purge google-chrome-stable
```

Then install chrome directly from the .deb file like this:
```bash
sudo dpkg -i google-chrome-stable_75.0.3770.142-1_amd64.deb
```

**Comment by Wingman4l7** [comment]
Never seen this error before either, but I have seen warnings elsewhere that you can get squirrelly behavior or errors if your installed version of Chrome doesn't match the version of the chromedriver binary that you install.  I'll add a note to the README, thanks!
